#main program
import exceptions

def main():
    exceptions.multiply_two_number_validate()
    

main()